### ISSUE TITLE
How to use  react-photo-grid in my component 

### ISSUE THREAD

**Issue by mrjosshi** [mukeshsoni/react-photo-grid#10]
Here is my code but images are not rendering in UI Please help how to use this in my component
TIA

import React, { Component } from "react";
import { withRouter } from "react-router-dom";
import ReactPhotoGrid from 'react-images';
import styles from "../style.scss";

class PhotoAlbumTemplate extends Component {
state = {

};

render() {
var that = this;
//const cardImageStatus = that.props.hasImage;
var imageData = [
'http://via.placeholder.com/400x400/',
'http://via.placeholder.com/500x700/',
'http://via.placeholder.com/600x500/',
'http://via.placeholder.com/600x800/'
];

return (<section>
 <ReactPhotoGrid
        data={imageData}
    />
</section>)
}
}
export default withRouter(PhotoAlbumTemplate);

**Comment by mukeshsoni** [comment]
This is not a react-photo-grid issue. Please ask this question on stackoverflow.
