### ISSUE TITLE
photos limited to only 4 ?

### ISSUE THREAD

**Issue by sahanDissanayake** [mukeshsoni/react-photo-grid#2]

**Comment by mukeshsoni** [comment]
Yup, current implementation shows a max of 4 photos in the grid

**Comment by sahanDissanayake** [comment]
thanks, any plans to set a prop to change the number of photos in the grid ?

**Comment by mukeshsoni** [comment]
no plans as of now

**Comment by infacq** [comment]
any plan to put some effect to show all the other image
