### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by foodaka** [mukeshsoni/react-photo-grid#3]
Tried to use this, cannot import it into my file. Maybe because of the old version of react? Will you update this ?

var ImageGrid = require('react-photo-grid');

import ImageGrid from 'react-photo-grid';

both dont work, would love to use this plugin

**Comment by mukeshsoni** [comment]
the require would surely work if you use webpack or any bundler which understands commonjs module format.

Can you tell me the exact problem? With error message.

**Comment by foodaka** [comment]
Module parse failed: /Users//work/site/node_modules/react-photo-grid/index.js Line 258: Unexpected token <
You may need an appropriate loader to handle this file type.
| 
|             return (
|                 <div key={'image_'+index} style={componentStyle}>
|                   <img
|                     style={imageStyle}
 @ ./src/components/discover.js 49:16-43

**Comment by mukeshsoni** [comment]
are you using a jsx transformer (using babel or webpack)? The index file has jsx in it. That is where the parsing fails.

**Comment by foodaka** [comment]
hey i got webpack and babel, i forked the the updated version from https://github.com/TomOlivier/react-photo-grid 

and that is working 

hopefully we can keep this project going

**Comment by mukeshsoni** [comment]
That's strange. The index.js file is exactly the same (except for top comment /*\* @jsx React.DOM */ and PropTypes var declaration).

PRs are surely welcome. Let me know if you have any ideas for improvement.

**Comment by foodaka** [comment]
Maybe I actually just took the index.js file

**Comment by empz** [comment]
Any updates on this? I'm getting the same error when bundling with webpack. Tried every possible way of importing/requiring.

**Comment by mukeshsoni** [comment]
@emzero you probably don't have the jsx loader. Try using the babel-loader - https://github.com/babel/babel-loader
