### ISSUE TITLE
Randomly photo change

### ISSUE THREAD

**Issue by infacq** [mukeshsoni/react-photo-grid#4]
Hi 

This is great component. I just wonder what if I have large of data sets, and I want it change the photo randomly using special effect like `fade`. Is it possible to achieve it?

**Comment by mukeshsoni** [comment]
Can you give a link to a similar example?

**Comment by infacq** [comment]
this one like facebook did on mobile apps

**Comment by infacq** [comment]
can you check this grid. http://tympanus.net/Development/AnimatedResponsiveImageGrid/index3.html

**Comment by mukeshsoni** [comment]
Not possible to achieve it currently. I will add an enhancement label and see if it's possible to do.

**Comment by infacq** [comment]
thanks

**Comment by mukeshsoni** [comment]
@infacq I looked at the effect again and think that it doesn't fit his component's goals. Will close it.
