### ISSUE TITLE
publish a compiled version

### ISSUE THREAD

**Issue by pradel** [mukeshsoni/react-photo-grid#6]
Hey, thank you for this package!
Can you publish a compiled version on npm?
Right now webpack fail to import the module since jsx is not compiled.

**Comment by mukeshsoni** [comment]
@pradel i can see your webpack config?

**Comment by Hanumashin** [comment]
@mukeshsoni thank you for package :)
@pradel check this out [babel-plugin-transform-react-jsx](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx)

**Comment by pradel** [comment]
My babel loader is excluding the node_modules folder, it's why it's not working.
```
loaders: [{
      test: /\.js$/,
      loaders: ['babel-loader'],
      exclude: /(node_modules\/)/,
    }
```

**Comment by mukeshsoni** [comment]
@pradel does excluding `node_modules` for loaders give you performance benefits?

**Comment by pradel** [comment]
Yeah it's why I am doing that. I managed to make it work by modifying the exclude to allow react-photo-grid.

**Comment by mukeshsoni** [comment]
Ok. Will close it then.

**Comment by pradel** [comment]
Thanks
