### ISSUE TITLE
Typo -- with quick fix

### ISSUE THREAD

**Issue by pbalogh** [mukeshsoni/react-photo-grid#7]
var containerStyle = {
            width: this.state.containerWidth,
            height: this.state.containerWidth,
            backgroundColor: 'white'
};

Should be:

var containerStyle = {
            width: this.state.containerWidth + "px",
            height: this.state.containerHeight + "px",
            backgroundColor: 'white'
};

**Comment by pbalogh** [comment]
Note that height was being set to this.state.containerWidth instead of this.state.containerHeight. Also, adding "px" seems to help React in sizing the component properly.

**Comment by pbalogh** [comment]
Another issue:

var smallestDimensionRaw = Math.floor(this.state['container' + winner]/(numberOfImages - 1));

should be

var smallestDimensionRaw = Math.floor(this.state['container' + loser]/(numberOfImages - 1));

If the winner is 'Height', then we're splitting this grid into vertical slices, each of which should be totalWidth / numberOfImages in width. So: when winner is 'Height', the the attribute we split is 'Width'

**Comment by mukeshsoni** [comment]
@pbalogh 
Adding "px" does not make a difference to react. All css pixel units can be sent as just numbers when setting style attribute in jsx.
